# docker-compose.yml
version: '3'

services:
  flask:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
#      args:
#        ARG: <ARG>
    image: "ift6758/serving:1.0.0"
    ports:
      - "9998:5000"
    environment:
      COMET_API_KEY: ${COMET_API_KEY}
###### Uncomment below when you're ready to add the final notebook container to your docker compose
  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
 #     args:
 #      ARG: <ARG>
    image: "ift6758/streamlit:1.0.0"
    ports:
      - "8501:8501"
    #environment:
    #  OTHER_DOCKER_ENV_VAR = ${OTHER_LOCAL_ENV_VAR}
      

     
