name: ift6758-project-conda-env
dependencies:
  - python=3.9
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - jupyterlab
  - matplotlib
  - seaborn
  - tqdm
  - requests
  - plotly
  - pip
  - pip:
    - comet_ml